

services:
  postgres:
    image: postgres:15
    container_name: postgres_projeto_aula03
    restart: always
    environment:
      POSTGRES_USER: usuario_exemplo
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: projetoAula03
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
